import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>@sodabaked</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <div className={styles.logoText}>soda backed</div>
        <div className={styles.avatar}></div>
      </header>
      <main className={styles.main}></main>
    </div>
  )
}
